In [ ]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Đọc dữ liệu
X = pd.read_csv('mnist_test.csv')
# print(X['label'])
# Chọn ngẫu nhiên 10,000 mẫu
# X = mnist_data.sample(n=N, random_state=42)
# Loại bỏ cột nhãn (giả sử cột nhãn tên là 'label')
X_features = X.drop(columns=['label'], errors='ignore')
# print(X_features)
K = 10
kmeans = KMeans(n_clusters=K, random_state=42)
kmeans.fit(X_features)
# image_data = X_features.iloc[0].values
# image_data = image_data[:784]
# image_data = image_data.reshape(28,28)
# plt.imshow(image_data, cmap='gray')
# Dự đoán nhãn cụm cho các điểm dữ liệu
pred_label = kmeans.predict(X_features)

In [1]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
img = mpimg.imread('girl3.jpg')
plt.imshow(img)
imgplot = plt.imshow(img)
plt.axis('off')
plt.show()
X = img.reshape((img.shape[0]*img.shape[1], img.shape[2]))
print(X)

[[10 12  9]
 [11 13 10]
 [12 14 11]
 ...
 [23 29 19]
 [22 28 16]
 [21 27 15]]


In [5]:
kmeans = KMeans(n_clusters=10, random_state=42,n_init=10)
kmeans.fit(X)
centroids = kmeans.cluster_centers_
label = kmeans.predict(X)
# print(label)
# label = label.reshape(img.shape[0], img.shape[1])
# labels = kmeans.labels_  # Nhãn của mỗi pixel
# print(labels)

# 📌 Bước 5: Thay thế mỗi pixel bằng màu của centroid tương ứng
new_img = centroids[label].reshape(img.shape)
# print(new_img)
plt.imshow(new_img.astype(np.uint8))
# 📌 Bước 6: Hiển thị ảnh đã phân cụm
# plt.imshow(new_img.astype(np.uint8))
plt.axis('off')

(np.float64(-0.5), np.float64(2047.5), np.float64(1288.5), np.float64(-0.5))