In [16]:
from __future__ import print_function
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
import numpy as np
# train data
d1 = [2, 1, 1, 0, 0, 0, 0, 0, 0]
d2 = [1, 1, 0, 1, 1, 0, 0, 0, 0]
d3 = [0, 1, 0, 0, 1, 1, 0, 0, 0]
d4 = [0, 1, 0, 0, 0, 0, 1, 1, 1]
train_data = np.array([d1,d2,d3,d4])
label = np.array(['B', 'B', 'B', 'N'])
# test data
d5 = np.array([[2, 0, 0, 1, 0, 0, 0, 1, 0]])
d6 = np.array([[0, 1, 0, 0, 0, 0, 0, 1, 1]])
model = MultinomialNB()
# training 
model.fit(train_data, label)
# test
print(model.predict(d5))
print(model.predict_proba(d6))
print(model.predict(d6))

['B']
[[0.29175335 0.70824665]]
['N']


In [23]:
d1 = [2, 1, 1, 0, 0, 0, 0, 0, 0]
d2 = [1, 1, 0, 1, 1, 0, 0, 0, 0]
d3 = [0, 1, 0, 0, 1, 1, 0, 0, 0]
d4 = [0, 1, 0, 0, 0, 0, 1, 1, 1]
train_data = np.array([d1, d2, d3,d4])
label = np.array(['B', 'B', 'B', 'N'])
model = BernoulliNB()
model.fit(train_data, label)
print(model.predict(d5))
print(model.predict_proba(d5))
print(model.predict(d6))
print(model.predict_proba(d6))

['B']
[[0.76554295 0.23445705]]
['N']
[[0.16948581 0.83051419]]
